export interface LocationData {
  id: string
  label: string
  city: string
  region: string
  country: string
  latitude: number
  longitude: number
  source: "device" | "manual"
}

export const MOCK_LOCATIONS: Omit<LocationData, "source">[] = [
  {
    id: "loc_surat",
    label: "Surat, Gujarat",
    city: "Surat",
    region: "Gujarat",
    country: "India",
    latitude: 21.1702,
    longitude: 72.8311,
  },
  {
    id: "loc_ahmedabad",
    label: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    region: "Gujarat",
    country: "India",
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    id: "loc_vadodara",
    label: "Vadodara, Gujarat",
    city: "Vadodara",
    region: "Gujarat",
    country: "India",
    latitude: 22.3072,
    longitude: 73.1812,
  },
  {
    id: "loc_rajkot",
    label: "Rajkot, Gujarat",
    city: "Rajkot",
    region: "Gujarat",
    country: "India",
    latitude: 22.3039,
    longitude: 70.8022,
  },
  {
    id: "loc_gandhinagar",
    label: "Gandhinagar, Gujarat",
    city: "Gandhinagar",
    region: "Gujarat",
    country: "India",
    latitude: 23.2156,
    longitude: 72.6369,
  },
  {
    id: "loc_bhavnagar",
    label: "Bhavnagar, Gujarat",
    city: "Bhavnagar",
    region: "Gujarat",
    country: "India",
    latitude: 21.7645,
    longitude: 72.1519,
  },
  {
    id: "loc_jamnagar",
    label: "Jamnagar, Gujarat",
    city: "Jamnagar",
    region: "Gujarat",
    country: "India",
    latitude: 22.4707,
    longitude: 70.0577,
  },
  {
    id: "loc_junagadh",
    label: "Junagadh, Gujarat",
    city: "Junagadh",
    region: "Gujarat",
    country: "India",
    latitude: 21.5222,
    longitude: 70.4579,
  },
  {
    id: "loc_anand",
    label: "Anand, Gujarat",
    city: "Anand",
    region: "Gujarat",
    country: "India",
    latitude: 22.5645,
    longitude: 72.9289,
  },
  {
    id: "loc_navsari",
    label: "Navsari, Gujarat",
    city: "Navsari",
    region: "Gujarat",
    country: "India",
    latitude: 20.9500,
    longitude: 72.9300,
  },
  {
    id: "loc_bharuch",
    label: "Bharuch, Gujarat",
    city: "Bharuch",
    region: "Gujarat",
    country: "India",
    latitude: 21.7051,
    longitude: 72.9959,
  },
  {
    id: "loc_valsad",
    label: "Valsad, Gujarat",
    city: "Valsad",
    region: "Gujarat",
    country: "India",
    latitude: 20.5992,
    longitude: 72.9342,
  },
  {
    id: "loc_mehsana",
    label: "Mehsana, Gujarat",
    city: "Mehsana",
    region: "Gujarat",
    country: "India",
    latitude: 23.5880,
    longitude: 72.3693,
  },
  {
    id: "loc_bhuj",
    label: "Bhuj, Gujarat",
    city: "Bhuj",
    region: "Gujarat",
    country: "India",
    latitude: 23.2420,
    longitude: 69.6669,
  },
  {
    id: "loc_mumbai",
    label: "Mumbai, Maharashtra",
    city: "Mumbai",
    region: "Maharashtra",
    country: "India",
    latitude: 19.0760,
    longitude: 72.8777,
  },
  {
    id: "loc_delhi",
    label: "New Delhi, Delhi",
    city: "New Delhi",
    region: "Delhi",
    country: "India",
    latitude: 28.6139,
    longitude: 77.2090,
  },
  {
    id: "loc_pune",
    label: "Pune, Maharashtra",
    city: "Pune",
    region: "Maharashtra",
    country: "India",
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    id: "loc_bengaluru",
    label: "Bengaluru, Karnataka",
    city: "Bengaluru",
    region: "Karnataka",
    country: "India",
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    id: "loc_hyderabad",
    label: "Hyderabad, Telangana",
    city: "Hyderabad",
    region: "Telangana",
    country: "India",
    latitude: 17.3850,
    longitude: 78.4867,
  },
  {
    id: "loc_jaipur",
    label: "Jaipur, Rajasthan",
    city: "Jaipur",
    region: "Rajasthan",
    country: "India",
    latitude: 26.9124,
    longitude: 75.7873,
  }
]
