import type { Organization, Doctor, Review } from "./types"

const STANDARD_HOURS = {
  "Monday": "9:00 AM – 8:00 PM",
  "Tuesday": "9:00 AM – 8:00 PM",
  "Wednesday": "9:00 AM – 8:00 PM",
  "Thursday": "9:00 AM – 8:00 PM",
  "Friday": "9:00 AM – 8:00 PM",
  "Saturday": "10:00 AM – 4:00 PM",
  "Sunday": "Closed"
}

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org_1",
    name: "CityCare Multispecialty Hospital",
    type: "Hospital",
    address: "SG Highway, Thaltej",
    city: "Ahmedabad",
    latitude: 23.0488,
    longitude: 72.5050,
    rating: 4.8,
    reviewCount: 324,
    specializations: ["Cardiologist", "Orthopedic", "General Physician"],
    doctorIds: ["doc_1", "doc_2"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 15 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "contact@citycare.example.com"
  },
  {
    id: "org_2",
    name: "Aura Skin & Hair Clinic",
    type: "Clinic",
    address: "C G Road, Navrangpura",
    city: "Ahmedabad",
    latitude: 23.0333,
    longitude: 72.5617,
    rating: 4.6,
    reviewCount: 128,
    specializations: ["Dermatologist"],
    doctorIds: ["doc_3"],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 2 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "hello@auraclinic.example.com"
  },
  {
    id: "org_3",
    name: "Sunshine Pediatric Center",
    type: "Clinic",
    address: "Prahlad Nagar",
    city: "Ahmedabad",
    latitude: 23.0120,
    longitude: 72.5108,
    rating: 4.9,
    reviewCount: 450,
    specializations: ["Pediatrician"],
    doctorIds: ["doc_4"],
    availability: { status: "full", nextAvailable: "Next week", availableSlots: 0 },
    onlineConsultation: false,
    workingHours: STANDARD_HOURS,
    contact: "care@sunshinepeds.example.com"
  },
  {
    id: "org_4",
    name: "Surat General Hospital",
    type: "Hospital",
    address: "Ring Road",
    city: "Surat",
    latitude: 21.1702,
    longitude: 72.8311,
    rating: 4.5,
    reviewCount: 890,
    specializations: ["General Physician", "Orthopedic", "Gynecologist"],
    doctorIds: ["doc_5"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 45 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@suratgeneral.example.com"
  },
  {
    id: "org_5",
    name: "Ahmedabad Care Hospital",
    type: "Hospital",
    address: "Vastrapur",
    city: "Ahmedabad",
    latitude: 23.0350,
    longitude: 72.5300,
    rating: 4.3,
    reviewCount: 512,
    specializations: ["General Physician", "Neurologist"],
    doctorIds: [],
    availability: { status: "full", nextAvailable: "Tomorrow", availableSlots: 0 },
    onlineConsultation: false,
    workingHours: STANDARD_HOURS,
    contact: "care@ahmedabadcare.example.com"
  },
  {
    id: "org_6",
    name: "Elite Dental Clinic",
    type: "Clinic",
    address: "Drive-in Road",
    city: "Ahmedabad",
    latitude: 23.0450,
    longitude: 72.5400,
    rating: 4.8,
    reviewCount: 201,
    specializations: ["Dentist"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 10 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "hello@elitedental.example.com"
  },
  {
    id: "org_7",
    name: "Vision Eye Center",
    type: "Clinic",
    address: "Satellite",
    city: "Ahmedabad",
    latitude: 23.0250,
    longitude: 72.5200,
    rating: 4.7,
    reviewCount: 310,
    specializations: ["Ophthalmologist"],
    doctorIds: [],
    availability: { status: "limited", nextAvailable: "Today", availableSlots: 1 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@visioneye.example.com"
  },
  {
    id: "org_8",
    name: "Hope Women's Hospital",
    type: "Hospital",
    address: "Bodakdev",
    city: "Ahmedabad",
    latitude: 23.0300,
    longitude: 72.5100,
    rating: 4.9,
    reviewCount: 840,
    specializations: ["Gynecologist", "Pediatrician"],
    doctorIds: [],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 3 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "contact@hopewomens.example.com"
  }
]

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "doc_1",
    name: "Dr. Rajesh Patel",
    specialization: "Cardiologist",
    organizationId: "org_1",
    rating: 4.9,
    reviewCount: 156,
    experience: 15,
    qualifications: ["MBBS", "MD - Cardiology"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 5 },
    reviewIds: ["rev_1", "rev_2"]
  },
  {
    id: "doc_2",
    name: "Dr. Sneha Desai",
    specialization: "General Physician",
    organizationId: "org_1",
    rating: 4.7,
    reviewCount: 89,
    experience: 8,
    qualifications: ["MBBS", "MD - Internal Medicine"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 2 },
    reviewIds: []
  },
  {
    id: "doc_3",
    name: "Dr. Ananya Shah",
    specialization: "Dermatologist",
    organizationId: "org_2",
    rating: 4.6,
    reviewCount: 128,
    experience: 10,
    qualifications: ["MBBS", "DDVL"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 2 },
    reviewIds: []
  },
  {
    id: "doc_4",
    name: "Dr. Vikram Joshi",
    specialization: "Pediatrician",
    organizationId: "org_3",
    rating: 4.9,
    reviewCount: 450,
    experience: 20,
    qualifications: ["MBBS", "MD - Pediatrics"],
    consultationTypes: ["Physical"],
    availability: { status: "full", nextAvailable: "Next week", availableSlots: 0 },
    reviewIds: ["rev_3"]
  },
  {
    id: "doc_5",
    name: "Dr. Amit Verma",
    specialization: "Orthopedic",
    organizationId: "org_4",
    rating: 4.5,
    reviewCount: 300,
    experience: 12,
    qualifications: ["MBBS", "MS - Orthopedics"],
    consultationTypes: ["Physical"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 8 },
    reviewIds: []
  }
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev_1",
    author: "Rahul S.",
    rating: 5,
    text: "Dr. Patel was extremely thorough and took the time to explain everything clearly. Highly recommended.",
    date: "2024-05-15T10:00:00Z",
    verifiedAppointment: true,
    doctorId: "doc_1",
    organizationId: "org_1"
  },
  {
    id: "rev_2",
    author: "Neha K.",
    rating: 4,
    text: "Great facility and minimal waiting time. The consultation was helpful.",
    date: "2024-06-02T14:30:00Z",
    verifiedAppointment: true,
    doctorId: "doc_1",
    organizationId: "org_1"
  },
  {
    id: "rev_3",
    author: "Priya M.",
    rating: 5,
    text: "My kids love Dr. Joshi. He is very patient and knowledgeable. Only downside is getting an appointment is tough because he is so busy!",
    date: "2024-06-10T09:15:00Z",
    verifiedAppointment: true,
    doctorId: "doc_4",
    organizationId: "org_3"
  }
]
