import type { Organization, Doctor, Review } from "./types"

const STANDARD_HOURS = {
  "Monday": "Open 24 Hours",
  "Tuesday": "Open 24 Hours",
  "Wednesday": "Open 24 Hours",
  "Thursday": "Open 24 Hours",
  "Friday": "Open 24 Hours",
  "Saturday": "Open 24 Hours",
  "Sunday": "Open 24 Hours"
}

const CLINIC_HOURS = {
  "Monday": "9:00 AM – 8:00 PM",
  "Tuesday": "9:00 AM – 8:00 PM",
  "Wednesday": "9:00 AM – 8:00 PM",
  "Thursday": "9:00 AM – 8:00 PM",
  "Friday": "9:00 AM – 8:00 PM",
  "Saturday": "10:00 AM – 4:00 PM",
  "Sunday": "Closed"
}

export const MOCK_ORGANIZATIONS: Organization[] = [
  // ===================== SURAT HOSPITALS =====================
  {
    id: "org_surat_1",
    name: "Kiran Multi Super Speciality Hospital",
    type: "Hospital",
    address: "Vasta Devdi Rd, Near Sumul Dairy Road, Katargam",
    city: "Surat",
    latitude: 21.2226,
    longitude: 72.8339,
    rating: 4.8,
    reviewCount: 58200,
    specializations: ["Cardiology", "Neurology", "Orthopedic", "General Physician", "Oncology"],
    doctorIds: ["doc_surat_1", "doc_surat_2"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 32 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@kiranhospital.com"
  },
  {
    id: "org_surat_2",
    name: "Shalby Multi-Specialty Hospital",
    type: "Hospital",
    address: "Nr. Navyug College, Rander Rd",
    city: "Surat",
    latitude: 21.1985,
    longitude: 72.7981,
    rating: 4.8,
    reviewCount: 13400,
    specializations: ["Orthopedic", "Joint Replacement", "Cardiology", "General Physician"],
    doctorIds: ["doc_surat_3"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 24 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "contact@shalbysurat.com"
  },
  {
    id: "org_surat_3",
    name: "Universal Hospital | Multispeciality & Trauma",
    type: "Hospital",
    address: "Ring Rd, near Sub-Jail",
    city: "Surat",
    latitude: 21.1895,
    longitude: 72.8423,
    rating: 4.7,
    reviewCount: 1150,
    specializations: ["General Physician", "Trauma", "Critical Care", "Gynecologist"],
    doctorIds: ["doc_surat_4"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 18 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "care@universalhospitalsurat.com"
  },
  {
    id: "org_surat_4",
    name: "Smt. Rasilaben Sevantilal Shah Venus Hospital",
    type: "Hospital",
    address: "Ashakatashram Campus, SRSS Venus Hospital, Lal Darwaja",
    city: "Surat",
    latitude: 21.2052,
    longitude: 72.8270,
    rating: 4.9,
    reviewCount: 4820,
    specializations: ["General Physician", "Pediatrician", "Cardiologist", "Surgery"],
    doctorIds: ["doc_surat_5"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 28 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@venushospital.org"
  },
  {
    id: "org_surat_5",
    name: "LifeLine Multispeciality Hospital",
    type: "Hospital",
    address: "Palanpur Jakatnaka, Rander Road",
    city: "Surat",
    latitude: 21.2180,
    longitude: 72.7885,
    rating: 4.7,
    reviewCount: 2300,
    specializations: ["General Physician", "Orthopedic", "ENT"],
    doctorIds: ["doc_surat_6"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 14 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@lifelinesurat.com"
  },
  {
    id: "org_surat_6",
    name: "BAPS Pramukh Swami Hospital",
    type: "Hospital",
    address: "Anand Mahal Road, Adajan",
    city: "Surat",
    latitude: 21.1920,
    longitude: 72.7925,
    rating: 4.8,
    reviewCount: 9400,
    specializations: ["Cardiology", "Nephrology", "General Physician", "Pediatrician"],
    doctorIds: ["doc_surat_7"],
    availability: { status: "limited", nextAvailable: "Today", availableSlots: 6 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "care@bapshospitalsurat.org"
  },
  {
    id: "org_surat_7",
    name: "Apple Maitreya Hospital",
    type: "Hospital",
    address: "Ring Road, near Khatodara GIDC, Majura Gate",
    city: "Surat",
    latitude: 21.1730,
    longitude: 72.8210,
    rating: 4.6,
    reviewCount: 3100,
    specializations: ["Cardiology", "Oncology", "Critical Care", "Neurology"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 19 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "contact@applemaitreya.com"
  },
  {
    id: "org_surat_8",
    name: "Unity Hospital & Unity Trauma Centre",
    type: "Hospital",
    address: "Aai Mata Road, Parvat Patiya",
    city: "Surat",
    latitude: 21.1905,
    longitude: 72.8680,
    rating: 4.7,
    reviewCount: 2850,
    specializations: ["Trauma", "Orthopedic", "General Physician", "Neurosurgery"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 22 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "support@unityhospital.in"
  },
  {
    id: "org_surat_9",
    name: "Unique Hospital & Research Centre",
    type: "Hospital",
    address: "Civil Char Rasta, Near Ghod Dod Road",
    city: "Surat",
    latitude: 21.1620,
    longitude: 72.8080,
    rating: 4.6,
    reviewCount: 1900,
    specializations: ["Urology", "Gastroenterology", "General Physician"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 15 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "help@uniquehospital.org"
  },
  {
    id: "org_surat_10",
    name: "Mahavir Hospital & Heart Institute",
    type: "Hospital",
    address: "Athwa Gate, Ring Road, Nanpura",
    city: "Surat",
    latitude: 21.1810,
    longitude: 72.8055,
    rating: 4.7,
    reviewCount: 5600,
    specializations: ["Cardiology", "Cardiac Surgery", "General Physician"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 27 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@mahavirhospital.org"
  },
  {
    id: "org_surat_11",
    name: "Param Superspeciality Hospital",
    type: "Specialty Clinic",
    address: "Katargam Main Road",
    city: "Surat",
    latitude: 21.2150,
    longitude: 72.8390,
    rating: 4.6,
    reviewCount: 1400,
    specializations: ["General Physician", "Pediatrician", "Dermatologist"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 11 },
    onlineConsultation: true,
    workingHours: CLINIC_HOURS,
    contact: "contact@paramhospital.com"
  },
  {
    id: "org_surat_12",
    name: "Velocity Multispeciality Hospital",
    type: "Hospital",
    address: "Gaurav Path, Adajan",
    city: "Surat",
    latitude: 21.1970,
    longitude: 72.7840,
    rating: 4.8,
    reviewCount: 2100,
    specializations: ["General Physician", "Orthopedic", "Gynecologist"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 17 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "care@velocityhospital.com"
  },
  {
    id: "org_surat_13",
    name: "Nirmal Super Speciality Hospital",
    type: "Hospital",
    address: "Near Prime Arcade, Anand Mahal Road, Adajan",
    city: "Surat",
    latitude: 21.1950,
    longitude: 72.7890,
    rating: 4.7,
    reviewCount: 1800,
    specializations: ["Pediatrician", "Neonatology", "General Physician"],
    doctorIds: [],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 12 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "info@nirmalhospital.com"
  },

  // ===================== AHMEDABAD HOSPITALS =====================
  {
    id: "org_1",
    name: "CityCare Multispecialty Hospital",
    type: "Hospital",
    address: "SG Highway, Thaltej",
    city: "Ahmedabad",
    latitude: 23.0488,
    longitude: 72.5050,
    rating: 4.8,
    reviewCount: 324,
    specializations: ["Cardiologist", "Orthopedic", "General Physician"],
    doctorIds: ["doc_1", "doc_2"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 15 },
    onlineConsultation: true,
    workingHours: STANDARD_HOURS,
    contact: "contact@citycare.example.com"
  },
  {
    id: "org_2",
    name: "Aura Skin & Hair Clinic",
    type: "Clinic",
    address: "C G Road, Navrangpura",
    city: "Ahmedabad",
    latitude: 23.0333,
    longitude: 72.5617,
    rating: 4.6,
    reviewCount: 128,
    specializations: ["Dermatologist"],
    doctorIds: ["doc_3"],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 2 },
    onlineConsultation: true,
    workingHours: CLINIC_HOURS,
    contact: "hello@auraclinic.example.com"
  },
  {
    id: "org_3",
    name: "Sunshine Pediatric Center",
    type: "Clinic",
    address: "Prahlad Nagar",
    city: "Ahmedabad",
    latitude: 23.0120,
    longitude: 72.5108,
    rating: 4.9,
    reviewCount: 450,
    specializations: ["Pediatrician"],
    doctorIds: ["doc_4"],
    availability: { status: "full", nextAvailable: "Next week", availableSlots: 0 },
    onlineConsultation: false,
    workingHours: CLINIC_HOURS,
    contact: "care@sunshinepeds.example.com"
  }
]

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "doc_surat_1",
    name: "Dr. Hiren Kevadiya",
    specialization: "Cardiologist",
    organizationId: "org_surat_1",
    rating: 4.9,
    reviewCount: 420,
    experience: 16,
    qualifications: ["MBBS", "MD", "DM - Cardiology"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 12 },
    reviewIds: ["rev_s1"]
  },
  {
    id: "doc_surat_2",
    name: "Dr. Meera Patel",
    specialization: "General Physician",
    organizationId: "org_surat_1",
    rating: 4.8,
    reviewCount: 290,
    experience: 11,
    qualifications: ["MBBS", "MD - Internal Medicine"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 15 },
    reviewIds: []
  },
  {
    id: "doc_surat_3",
    name: "Dr. Vikramaditya Shah",
    specialization: "Orthopedic",
    organizationId: "org_surat_2",
    rating: 4.9,
    reviewCount: 650,
    experience: 20,
    qualifications: ["MBBS", "MS - Orthopedics", "MCh"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 8 },
    reviewIds: []
  },
  {
    id: "doc_surat_4",
    name: "Dr. Jayesh Vaghela",
    specialization: "General Physician",
    organizationId: "org_surat_3",
    rating: 4.7,
    reviewCount: 180,
    experience: 9,
    qualifications: ["MBBS", "MD"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 10 },
    reviewIds: []
  },
  {
    id: "doc_surat_5",
    name: "Dr. Pooja Mehta",
    specialization: "Pediatrician",
    organizationId: "org_surat_4",
    rating: 4.9,
    reviewCount: 310,
    experience: 14,
    qualifications: ["MBBS", "DCH", "MD - Pediatrics"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 14 },
    reviewIds: []
  },
  {
    id: "doc_1",
    name: "Dr. Rajesh Patel",
    specialization: "Cardiologist",
    organizationId: "org_1",
    rating: 4.9,
    reviewCount: 156,
    experience: 15,
    qualifications: ["MBBS", "MD - Cardiology"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "available", nextAvailable: "Today", availableSlots: 5 },
    reviewIds: ["rev_1", "rev_2"]
  },
  {
    id: "doc_2",
    name: "Dr. Sneha Desai",
    specialization: "General Physician",
    organizationId: "org_1",
    rating: 4.7,
    reviewCount: 89,
    experience: 8,
    qualifications: ["MBBS", "MD - Internal Medicine"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 2 },
    reviewIds: []
  },
  {
    id: "doc_3",
    name: "Dr. Ananya Shah",
    specialization: "Dermatologist",
    organizationId: "org_2",
    rating: 4.6,
    reviewCount: 128,
    experience: 10,
    qualifications: ["MBBS", "DDVL"],
    consultationTypes: ["Physical", "Online"],
    availability: { status: "limited", nextAvailable: "Tomorrow", availableSlots: 2 },
    reviewIds: []
  },
  {
    id: "doc_4",
    name: "Dr. Vikram Joshi",
    specialization: "Pediatrician",
    organizationId: "org_3",
    rating: 4.9,
    reviewCount: 450,
    experience: 20,
    qualifications: ["MBBS", "MD - Pediatrics"],
    consultationTypes: ["Physical"],
    availability: { status: "full", nextAvailable: "Next week", availableSlots: 0 },
    reviewIds: ["rev_3"]
  }
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev_s1",
    author: "Ketan S.",
    rating: 5,
    text: "World-class facilities at Kiran Hospital. Very clean, fast emergency triage, and friendly doctors.",
    date: "2024-06-15T10:00:00Z",
    verifiedAppointment: true,
    doctorId: "doc_surat_1",
    organizationId: "org_surat_1"
  },
  {
    id: "rev_1",
    author: "Rahul S.",
    rating: 5,
    text: "Dr. Patel was extremely thorough and took the time to explain everything clearly. Highly recommended.",
    date: "2024-05-15T10:00:00Z",
    verifiedAppointment: true,
    doctorId: "doc_1",
    organizationId: "org_1"
  },
  {
    id: "rev_2",
    author: "Neha K.",
    rating: 4,
    text: "Great facility and minimal waiting time. The consultation was helpful.",
    date: "2024-06-02T14:30:00Z",
    verifiedAppointment: true,
    doctorId: "doc_1",
    organizationId: "org_1"
  },
  {
    id: "rev_3",
    author: "Priya M.",
    rating: 5,
    text: "My kids love Dr. Joshi. He is very patient and knowledgeable. Highly recommended pediatrician!",
    date: "2024-06-10T09:15:00Z",
    verifiedAppointment: true,
    doctorId: "doc_4",
    organizationId: "org_3"
  }
]
